all:
  hosts:
    pi-3-48d0.snooops.net:
      ansible_ssh_host: 192.168.1.30
    pi-4-6ly6.snooops.net:
      ansible_ssh_host: 192.168.1.21
    pi-4-44fh.snooops.net:
      ansible_ssh_host: 192.168.1.20
  children:
    homelab:
      children:
        pi_cluster:
          children:
            main:
              hosts:
                pi-3-48d0.snooops.net:
            worker:
              hosts:
                pi-4-6ly6.snooops.net:
                pi-4-44fh.snooops.net: