---
- name: setup ubuntu raspberry pi
  hosts: all
  vars:
    my_user: snooops
  roles:
    - role: linux-basic-install
    - role: docker-install
      vars:
        user_to_docker_group: "{{ my_user }}"
    # docker swarm baby - not using this type of setup now
    # - role: manage-portainer
    #   vars: 
    #     docker_user: "{{ my_user }}"
    
- name: create docker swarm
  hosts: manager[0]
  roles:
    - role: docker-swarm-create
  
- name: join worker
  hosts: worker
  roles:
    - role: docker-swarm-join