version: '3.8'
services: 
  portainer-agent:
    image: portainer/agent:2.18.4
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volume