version: "3.8"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pi-hole:
    image: pihole/pihole:2023.10.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=""
      - PIHOLE_DNS_=192.168.1.1
      - DNSSEC=true
      - DNS_BOGUS_PRIV=true
      - DNS_FQDN_REQUIRED=true
      - REV_SERVER=true
      - REV_SERVER_DOMAIN=snooops.net
      - REV_SERVER_TARGET=192.168.1.1
      - REV_SERVER_CIDR=192.168.1.0/24
      - DHCP_ACTIVE=false
      - PIHOLE_DOMAIN=snooops.net
      - IPv6=true
      - TEMPERATUREUNIT=c
      - WEBUIBOXEDLAYOUT=boxed
      - QUERY_LOGGING=true
      - WEBTHEME=default-dark
      - DNSMASQ_LISTENING=all
      - SKIPGRAVITYONBOOT=1
      - RATE_LIMIT=0/0
    volumes:
      - pi-hole_config:/etc/pihole'
      - pi-hole_dnsmasq:/etc/dnsmasq.d'

volumes:
  pi-hole_config:
  pi-hole_dnsmasq:
